config/routes.rb
Rails.application.routes.draw do
  get 'helo/index'
  get 'helo/add'
  get 'helo/edit'
  get 'helo/dell'
  get 'helo/list'

  devise_for :accounts
  
  get 'helo/login_check'
  get 'helo/index'
  get 'helo', to: 'helo#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
   has_many :helo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/helo.rb
class Helo < ActiveRecord::Base
 belongs_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/helo_controller.rb
class HeloController < ApplicationController
	layout 'application'
	before_action :authenticate_account!, only: :login_check
#	before_action :authenticate_account!

	def index
		@msg = 'this is sample page.'
		@data = Helo.all
	end
	
	def login_check
		@account = current_account
		@msg = 'you logined at: ' + @account.current_sign_in_at.to_s
	end

  def add
    @msg = "add new data."
    @helo = Helo.new
  end
  
  def create
    @helo = Helo.new helo_params
    if @helo.save then 
          redirect_to '/helo'
          return
    end
       render 'add'
  end

  def edit
    @msg = "edit data.[id = " + params[:id] + "]"
    @helo = Helo.find(params[:id])
#    if request.patch? then 
#       @helo.update(helo_params)
#     goback
#    end
  end

  def dell
    		@msg = 'this is sample page dell.'
   obj = helo.find(helo[:id])
   obj.update(helo_params)
   redirect_to '/helos'
  end
 

  def list
    		@msg = 'this is sample page list.'
    		@data = Helo.all
###    @helo = Helo.find(params[:id])
###    @data = Helo.find(params[:id])
  end

private
def helo_params
   params.require(:helo).permit(:account_id, :kubun, :word )
end

def goback
  redirect_to '/helo/index'
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/views/helo/add.html.erb
<h1>Helo#add</h1>
<p>Find me in app/views/helo/add.html.erb</p>
<h1>Comments#add</h1>
<p>Find me in app/views/comments/add.html.erb</p>
<p><%= @msg %></p>

<% if @helo.errors.any? %>
<ul>
	<% @account.errors.full_helo.each do |err| %>
	<li><%= err %></li>
	<% end %>
</ul>
<% end %>

<table>
	<%= form_for(@helo, url:{controller:'helo', action:'create' }) do |form| %>
	<tr><th>id</th>
	<td><%= form.text_field :id %></td></tr>
	<tr><th>talker_id</th>
		<td><%= form.text_field :account_id %></td></tr>
	<tr><th>ts</th>
		<td><%= form.text_field :ts %></td></tr>
	</tr>
	<tr><th></th>
			<td><%= form.text_field :kubun %></td></tr>
	</tr>
	<tr><th></th>
			<td><%= form.text_field :word %></td></tr>
	</tr>
	<tr><th></th>
		<td><%= form.submit "送信" %></td></tr>
	</tr>
	<% end %>
</table>

app/views/helo/dell.html.erb
<h1>Helo#dell</h1>
<p>Find me in app/views/helo/dell.html.erb</p>

app/views/helo/edit.html.erb
<h1>Helo#edit</h1>
<p>Find me in app/views/helo/edit.html.erb</p>

app/views/helo/index.html.erb
<h1>Helo#index</h1>
<p>Find me in app/views/helo/index.html.erb</p>

<h2>views/helo/index.html.erb</h2>
<h1>Helo#index</h1>
<p><%= @msg %></p>

<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>
<p><%= @msg %></p>
<pre>
<table>
	<tr>
		<th>投稿#</th><th>名前</th><th>日時</th><th>区分</th><th>コメント</th></th>
	</tr>
	<% @data.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
        <td><%= obj.account.email %></td>
		<td><%= obj.ts %></td>
		<td><%= obj.kubun %></td>
		<td><%= obj.word %></td>
	</tr>
	<% end %>
</table>
</pre>
<hr>
<div><%=link_to 'go to login_check page!&gt;&gt;'.html_safe, {action:'login_check'} %></div>
<div><%= link_to "Sign out&gt;&gt;".html_safe, destroy_account_session_path, method: :delete %></div>

app/views/helo/list.html.erb
<h1>Helo#list</h1>
<p>Find me in app/views/helo/list.html.erb</p>

app/views/helo/login_check.html.erb
<h2>views/helo/login_check.html.erb</h2>

<h1><%= @account.email %></h1>
<p><%= @msg %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/helo.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @title %></title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'application', media: 'all', 
		'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 
		'data-turbolinks-track': 'reload' %>
</head>


<body>
	<%= render template:'layouts/helo_header' %>
	<%= yield %>
	<div>　</div>
	<hr size="1" color="#aaa">
	<%= render template:'layouts/helo_footer' %>
</body>
</html>

app/views/layouts/helo_footer.html.erb
<div style="text-align:right; font-size:9pt;">
	<%= @footer %>
</div>

app/views/layouts/helo_header.html.erb
<h1 style="font-size:22pt;color:#ffaaaa;">
	<%= @header %>
</h1>